#!/bin/bash

CONFIG="$HOME/.github-credentials"

if [ ! -f "$CONFIG" ]; then
	echo "Config file '$CONFIG' does not exist"
	exit 1
fi

set -a
. "$CONFIG"
set +a

if [ -z $GITHUB_USER ]; then
	echo "GITHUB_USER not set in '$CONFIG'"
	exit 1
fi

if [ -z $GITHUB_EMAIL ]; then
        echo "GITHUB_EMAIL not set in '$CONFIG'"
        exit 1
fi

if [ -d .git ]; then
	git config user.email "$GITHUB_EMAIL" && echo "Git user.email was set to '$GITHUB_EMAIL'"
	git config user.name "$GITHUB_USER" && echo "Git user.name was set to '$GITHUB_USER'"
else
	echo "Current folder '$PWD' is not a valid git repo"
fi
